import { useEffect, useState } from "react";
import { Configuration, FrontendApi } from "@ory/client";

// Initialize the Ory Kratos client
const ory = new FrontendApi(
  new Configuration({
    basePath: "http://localhost/.ory/kratos",
    baseOptions: {
      withCredentials: true,
    },
  })
);

function Login() {
  const [flow, setFlow] = useState<any>(null);
  const [challenge, setChallenge] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const loginChallenge = params.get("login_challenge");

    if (loginChallenge) {
      setChallenge(loginChallenge);
    }

    // Create a new Kratos login flow
    ory
      .createBrowserLoginFlow()
      .then(({ data }) => setFlow(data))
      .catch((err) => {
        console.error("Failed to create login flow", err.response?.data || err);
        // If the user already has a valid session, Kratos throws a 400 "session_already_available" error
        if (err.response?.status === 400 && err.response?.data?.error?.id === "session_already_available") {
          if (loginChallenge) {
            window.location.href = `http://localhost/api/login?login_challenge=${loginChallenge}`;
          } else {
            window.location.href = "/";
          }
        } else {
          setError("Failed to initialize login flow.");
        }
      });
  }, []);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!flow) return;

    const formData = new FormData(e.currentTarget);
    const identifier = formData.get("identifier") as string;
    const password = formData.get("password") as string;

    // Extract CSRF token generated by Kratos
    const csrfToken = flow.ui.nodes.find(
      (node: any) => node.attributes.name === "csrf_token"
    )?.attributes.value;

    // Submit credentials to Kratos
    ory
      .updateLoginFlow({
        flow: flow.id,
        updateLoginFlowBody: {
          method: "password",
          identifier,
          password,
          csrf_token: csrfToken,
        },
      })
      .then(() => {
        // Authentication successful! The browser now has a valid Kratos session cookie.
        // Redirect back to the Express backend to finalize the Hydra OAuth2 login challenge.
        if (challenge) {
          window.location.href = `http://localhost/api/login?login_challenge=${challenge}`;
        } else {
          window.location.href = "/";
        }
      })
      .catch((err) => {
        console.error("Login failed", err.response?.data);
        if (err.response?.status === 400) {
          setFlow(err.response.data);
          setError("Invalid credentials. Please try again.");
        } else {
          setError("An unexpected error occurred.");
        }
      });
  };

  if (error && !flow) {
    return <div style={{ padding: "20px", color: "red" }}><h2>Error</h2><p>{error}</p></div>;
  }

  if (!flow) return <h2>Loading login form...</h2>;

  return (
    <div style={{ padding: "20px" }}>
      <h2>Sign In</h2>
      {error && <p style={{ color: "red" }}>{error}</p>}
      <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: "10px", width: "300px" }}>
        <div>
          <label>Email / Username:</label><br />
          <input name="identifier" type="text" required style={{ width: "100%" }} />
        </div>
        <div>
          <label>Password:</label><br />
          <input name="password" type="password" required style={{ width: "100%" }} />
        </div>
        <button type="submit">Sign In</button>
      </form>
    </div>
  );
}

export default Login;