apiVersion: v1
kind: Secret
metadata:
  name: zot-secret
  namespace: default
type: Opaque
stringData:
  credentials.json: |
    {
      "clientid": "zot-client",
      "clientsecret": "zot-secret-value"
    }