apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-proxy-config
  namespace: default
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/log/nginx/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        server {
            listen 8080;
            location / {
                # Route to Traefik in the default namespace
                proxy_pass http://traefik.default.svc.cluster.local:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
    stream {
        server {
            listen 8443;
            proxy_pass traefik.default.svc.cluster.local:8443;
        }
    }