apiVersion: v1
kind: Secret
metadata:
  name: zot-secret
  namespace: default
type: Opaque
stringData:
  credentials.json: |
    {
      "clientid": "zot-client",
      "clientsecret": "zot-secret-value"
    }
  htpasswd: |
    admin:$2y$05$SBmw8zR/IaqDQuIkNjYxTufrQLjw5vs0jpcDNh847i4b.e9wZHqp2