apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: default
data:
  init.sql: |
    CREATE DATABASE hydra;
    CREATE DATABASE kratos;
    CREATE USER ory WITH PASSWORD 'secret';
    GRANT ALL PRIVILEGES ON DATABASE hydra TO ory;
    GRANT ALL PRIVILEGES ON DATABASE kratos TO ory;

    -- Give ownership of DB to ory
    ALTER DATABASE hydra OWNER TO ory;
    ALTER DATABASE kratos OWNER TO ory;

    -- Connect to hydra DB
    \c hydra

    -- Give schema permissions
    GRANT ALL ON SCHEMA public TO ory;
    ALTER SCHEMA public OWNER TO ory;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ory;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ory;

    -- Switch to kratos DB
    \c kratos

    -- Give schema access
    GRANT ALL ON SCHEMA public TO ory;
    ALTER SCHEMA public OWNER TO ory;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ory;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ory;
    GRANT CREATE ON SCHEMA public TO ory;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgrespassword
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
